# -*- coding: utf-8 -*-
"""NLTK_tool.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yNmHJXHiviOqVY815bZuRyKw592Ze9fG

Text Preprocessing using NLTK Tool
"""

from nltk import sent_tokenize,word_tokenize

import nltk

nltk.download('punkt')

text = "Rohit is playing Excellent Cricket.\n Well played My Guy!"

print(sent_tokenize(text))

print(word_tokenize(text))

"""Tokenization with Ngram"""

from nltk import ngrams

text = "Ram and Sam are best buddies."

print(ngrams(word_tokenize(text),5))

for gram in ngrams(word_tokenize(text),5):
  print(gram)

"""Tokenization with Regular Expression"""

I_text="Hema and Reena are playing together also they are enjoying."

from nltk.tokenize import RegexpTokenizer

tk=RegexpTokenizer('\s+',gaps=False)

fg = "Mood is Good"

g = tk.tokenize(fg)

print(g)

